spring:
  application:
    name: shopping-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping-platform
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration
